// SPDX-License-Identifier: LGPL-3.0-or-later
// Copyright (C) 2026 Chris Bailey
// Part of Peregrine, a cross-platform port of FalconView(tm).
// See COPYING.LESSER and NOTICE.md for the full licensing picture.

#include "fv_desk_map_groups.h"

#include <algorithm>
#include <cctype>
#include <fstream>
#include <map>
#include <sstream>

#include <nlohmann/json.hpp>

#include "fvkit/catalog/catalog.h"

namespace fv {
namespace desk {
namespace {

// Generated by CMake from map-groups.json: kBuiltinMapGroupsJson.
#include "fv_desk_map_groups_builtin.inc"

using json = nlohmann::json;

bool StartsWithNoCase(const std::string& s, const std::string& prefix) {
  if (s.size() < prefix.size()) return false;
  for (size_t i = 0; i < prefix.size(); ++i)
    if (std::tolower(static_cast<unsigned char>(s[i])) !=
        std::tolower(static_cast<unsigned char>(prefix[i])))
      return false;
  return true;
}

}  // namespace

double MapGroup::NominalScaleOf(const std::string& format,
                                const std::string& series_key) const {
  for (const NominalScale& ns : nominal_scales) {
    if (!ns.format.empty() && ns.format != format) continue;
    if (!ns.prefix && ns.series.size() != series_key.size()) continue;
    if (StartsWithNoCase(series_key, ns.series)) return ns.scale_denom;
  }
  return 0;
}

MapGroups MapGroups::Builtin() {
  MapGroups g;
  g.LoadJson(kBuiltinMapGroupsJson, "map-groups.json");
  return g;
}

Status MapGroups::LoadJson(const std::string& text, const std::string& name) {
  auto fail = [&name](const std::string& why) {
    return Status::Error(kInvalidArg, name + ": " + why);
  };
  json doc = json::parse(text, nullptr, /*allow_exceptions=*/false);
  if (doc.is_discarded()) return fail("not valid JSON");
  if (!doc.is_object() || !doc.contains("groups") || !doc["groups"].is_array())
    return fail("expected an object with a \"groups\" array");

  std::vector<MapGroup> out;
  std::map<std::string, std::string> owner;  // format -> group id
  for (const json& jg : doc["groups"]) {
    if (!jg.is_object()) return fail("every group must be an object");
    MapGroup g;
    if (!jg.contains("id") || !jg["id"].is_string() || jg["id"].get<std::string>().empty())
      return fail("a group has no id");
    g.id = jg["id"].get<std::string>();
    for (const MapGroup& seen : out)
      if (seen.id == g.id) return fail("group '" + g.id + "' appears twice");
    g.title = jg.value("title", g.id);
    if (!jg.contains("formats") || !jg["formats"].is_array() || jg["formats"].empty())
      return fail("group '" + g.id + "' lists no formats");
    for (const json& f : jg["formats"]) {
      if (!f.is_string()) return fail("group '" + g.id + "' has a non-string format");
      const std::string key = f.get<std::string>();
      auto it = owner.find(key);
      if (it != owner.end())
        return fail("format '" + key + "' is in both '" + it->second + "' and '" + g.id + "'");
      owner[key] = g.id;
      g.formats.push_back(key);
    }
    const std::string ladder = jg.value("ladder", "uniform");
    if (ladder == "series") {
      g.ladder = view::LadderKind::kSeries;
    } else if (ladder == "uniform") {
      g.ladder = view::LadderKind::kUniform;
    } else {
      return fail("group '" + g.id + "' has unknown ladder '" + ladder + "'");
    }
    if (jg.contains("step")) {
      if (!jg["step"].is_number() || !(jg["step"].get<double>() > 1.0))
        return fail("group '" + g.id + "' step must be a number > 1");
      g.uniform_factor = jg["step"].get<double>();
    }
    if (jg.contains("scales")) {
      if (!jg["scales"].is_array()) return fail("group '" + g.id + "' scales must be an array");
      for (const json& js : jg["scales"]) {
        const std::string where = "group '" + g.id + "' scale entry";
        if (!js.is_object()) return fail(where + " must be an object");
        NominalScale ns;
        const bool has_series = js.contains("series"), has_prefix = js.contains("prefix");
        if (has_series && has_prefix) return fail(where + " has both series and prefix");
        if (has_series || has_prefix) {
          const json& key = has_series ? js["series"] : js["prefix"];
          if (!key.is_string() || key.get<std::string>().empty())
            return fail(where + " has an empty series or prefix");
          ns.series = key.get<std::string>();
          ns.prefix = has_prefix;
        } else if (!js.contains("format")) {
          return fail(where + " needs a series, a prefix or a format");
        } else {
          ns.prefix = true;  // an empty prefix matches every series of the format
        }
        if (js.contains("format")) {
          if (!js["format"].is_string()) return fail(where + " format must be a string");
          ns.format = js["format"].get<std::string>();
          if (std::find(g.formats.begin(), g.formats.end(), ns.format) == g.formats.end())
            return fail(where + " names format '" + ns.format + "', not in the group");
        }
        if (!js.contains("scale") || !js["scale"].is_number() ||
            !(js["scale"].get<double>() > 0))
          return fail(where + " for '" + (ns.series.empty() ? ns.format : ns.series) +
                      "' needs a scale > 0");
        ns.scale_denom = js["scale"].get<double>();
        g.nominal_scales.push_back(std::move(ns));
      }
    }
    out.push_back(std::move(g));
  }
  groups_ = std::move(out);
  return Status::Ok();
}

Status MapGroups::LoadFile(const std::string& path) {
  std::ifstream in(path, std::ios::binary);
  if (!in) return Status::Error(kNotFound, "cannot read " + path);
  std::ostringstream ss;
  ss << in.rdbuf();
  return LoadJson(ss.str(), path);
}

const MapGroup* MapGroups::Find(const std::string& id) const {
  for (const MapGroup& g : groups_)
    if (g.id == id) return &g;
  return nullptr;
}

const MapGroup* MapGroups::ForFormat(const std::string& format) const {
  for (const MapGroup& g : groups_)
    for (const std::string& f : g.formats)
      if (f == format) return &g;
  return nullptr;
}

std::vector<const MapGroup*> MapGroups::WithData(
    const std::set<std::string>& formats_present) const {
  std::vector<const MapGroup*> out;
  for (const MapGroup& g : groups_) {
    for (const std::string& f : g.formats) {
      if (formats_present.count(f)) {
        out.push_back(&g);
        break;
      }
    }
  }
  return out;
}

std::set<std::string> CatalogFormats(const Catalog& catalog) {
  std::set<std::string> out;
  std::vector<std::string> formats;
  if (!catalog.CoveredFormats(&formats).ok()) return out;
  out.insert(formats.begin(), formats.end());
  return out;
}

}  // namespace desk
}  // namespace fv
