// SPDX-License-Identifier: LGPL-3.0-or-later
// Copyright (C) 2026 Chris Bailey
// Part of Peregrine, a cross-platform port of FalconView(tm).
// See COPYING.LESSER and NOTICE.md for the full licensing picture.

#include "fv_desk_map_groups.h"

#include <fstream>
#include <map>
#include <sstream>

#include <nlohmann/json.hpp>

#include "fvkit/catalog/catalog.h"

namespace fv {
namespace desk {
namespace {

// Generated by CMake from map-groups.json: kBuiltinMapGroupsJson.
#include "fv_desk_map_groups_builtin.inc"

using json = nlohmann::json;

}  // namespace

MapGroups MapGroups::Builtin() {
  MapGroups g;
  g.LoadJson(kBuiltinMapGroupsJson, "map-groups.json");
  return g;
}

Status MapGroups::LoadJson(const std::string& text, const std::string& name) {
  auto fail = [&name](const std::string& why) {
    return Status::Error(kInvalidArg, name + ": " + why);
  };
  json doc = json::parse(text, nullptr, /*allow_exceptions=*/false);
  if (doc.is_discarded()) return fail("not valid JSON");
  if (!doc.is_object() || !doc.contains("groups") || !doc["groups"].is_array())
    return fail("expected an object with a \"groups\" array");

  std::vector<MapGroup> out;
  std::map<std::string, std::string> owner;  // format -> group id
  for (const json& jg : doc["groups"]) {
    if (!jg.is_object()) return fail("every group must be an object");
    MapGroup g;
    if (!jg.contains("id") || !jg["id"].is_string() || jg["id"].get<std::string>().empty())
      return fail("a group has no id");
    g.id = jg["id"].get<std::string>();
    for (const MapGroup& seen : out)
      if (seen.id == g.id) return fail("group '" + g.id + "' appears twice");
    g.title = jg.value("title", g.id);
    if (!jg.contains("formats") || !jg["formats"].is_array() || jg["formats"].empty())
      return fail("group '" + g.id + "' lists no formats");
    for (const json& f : jg["formats"]) {
      if (!f.is_string()) return fail("group '" + g.id + "' has a non-string format");
      const std::string key = f.get<std::string>();
      auto it = owner.find(key);
      if (it != owner.end())
        return fail("format '" + key + "' is in both '" + it->second + "' and '" + g.id + "'");
      owner[key] = g.id;
      g.formats.push_back(key);
    }
    const std::string ladder = jg.value("ladder", "uniform");
    if (ladder == "series") {
      g.ladder = view::LadderKind::kSeries;
    } else if (ladder == "uniform") {
      g.ladder = view::LadderKind::kUniform;
    } else {
      return fail("group '" + g.id + "' has unknown ladder '" + ladder + "'");
    }
    if (jg.contains("step")) {
      if (!jg["step"].is_number() || !(jg["step"].get<double>() > 1.0))
        return fail("group '" + g.id + "' step must be a number > 1");
      g.uniform_factor = jg["step"].get<double>();
    }
    out.push_back(std::move(g));
  }
  groups_ = std::move(out);
  return Status::Ok();
}

Status MapGroups::LoadFile(const std::string& path) {
  std::ifstream in(path, std::ios::binary);
  if (!in) return Status::Error(kNotFound, "cannot read " + path);
  std::ostringstream ss;
  ss << in.rdbuf();
  return LoadJson(ss.str(), path);
}

const MapGroup* MapGroups::Find(const std::string& id) const {
  for (const MapGroup& g : groups_)
    if (g.id == id) return &g;
  return nullptr;
}

const MapGroup* MapGroups::ForFormat(const std::string& format) const {
  for (const MapGroup& g : groups_)
    for (const std::string& f : g.formats)
      if (f == format) return &g;
  return nullptr;
}

std::vector<const MapGroup*> MapGroups::WithData(
    const std::set<std::string>& formats_present) const {
  std::vector<const MapGroup*> out;
  for (const MapGroup& g : groups_) {
    for (const std::string& f : g.formats) {
      if (formats_present.count(f)) {
        out.push_back(&g);
        break;
      }
    }
  }
  return out;
}

std::set<std::string> CatalogFormats(const Catalog& catalog) {
  std::set<std::string> out;
  std::vector<std::string> formats;
  if (!catalog.CoveredFormats(&formats).ok()) return out;
  out.insert(formats.begin(), formats.end());
  return out;
}

}  // namespace desk
}  // namespace fv
