// SPDX-License-Identifier: LGPL-3.0-or-later
// Copyright (C) 2026 Chris Bailey
// Part of Peregrine, a cross-platform port of FalconView(tm).
// See COPYING.LESSER and NOTICE.md for the full licensing picture.

import AppKit
import CxxStdlib
import PeregrineCore

/// The Map or Overlay options window over `DeskHost`'s options model: the
/// pages in a sidebar and the selected page's fields generated by type, with
/// Restore Defaults, Cancel, Apply and OK. Holds no option values of its own;
/// a control re-reads its field from the host after every change, so a value
/// the core clamps shows clamped.
@MainActor
final class OptionsWindowController: NSWindowController, NSWindowDelegate,
    NSTableViewDataSource, NSTableViewDelegate {
    let host: fv.desk.DeskHost
    let kind: Int32
    /// Called once the window has closed and the model is discarded.
    var onClose: (() -> Void)?

    private let sidebar = NSTableView()
    private let form = NSStackView()
    private let applyButton = NSButton(title: "Apply", target: nil, action: nil)
    private var page: Int32 = 0
    /// The current page's controls and field indices, by key.
    private var controls: [String: NSView] = [:]
    private var fieldIndex: [String: Int32] = [:]

    init(host: fv.desk.DeskHost, kind: Int32) {
        self.host = host
        self.kind = kind
        let window = NSWindow(contentRect: NSRect(x: 0, y: 0, width: 680, height: 480),
                              styleMask: [.titled, .closable, .resizable],
                              backing: .buffered, defer: true)
        window.title = kind == fv.desk.kOptionsMap.rawValue ? "Map Options" : "Overlay Options"
        window.minSize = NSSize(width: 520, height: 320)
        window.tabbingMode = .disallowed
        super.init(window: window)
        window.delegate = self
        buildLayout(in: window)
        reload()
    }

    @available(*, unavailable)
    required init?(coder: NSCoder) { fatalError("init(coder:) is not used") }

    /// Re-reads the model after the core opened it afresh.
    func reload() {
        sidebar.reloadData()
        let count = host.OptionsPageCount(kind)
        if page >= count { page = 0 }
        if count > 0 { sidebar.selectRowIndexes([Int(page)], byExtendingSelection: false) }
        showPage()
    }

    // MARK: Layout

    private func buildLayout(in window: NSWindow) {
        let column = NSTableColumn(identifier: .init("page"))
        sidebar.addTableColumn(column)
        sidebar.headerView = nil
        sidebar.style = .sourceList
        sidebar.dataSource = self
        sidebar.delegate = self
        let sideScroll = NSScrollView()
        sideScroll.documentView = sidebar
        sideScroll.hasVerticalScroller = true
        sideScroll.drawsBackground = false

        form.orientation = .vertical
        form.alignment = .leading
        form.spacing = 10
        form.edgeInsets = NSEdgeInsets(top: 16, left: 20, bottom: 16, right: 20)
        let formScroll = NSScrollView()
        formScroll.hasVerticalScroller = true
        formScroll.drawsBackground = false
        let clip = FlippedClipView()
        clip.drawsBackground = false
        formScroll.contentView = clip
        formScroll.documentView = form
        form.translatesAutoresizingMaskIntoConstraints = false
        form.leadingAnchor.constraint(equalTo: clip.leadingAnchor).isActive = true
        form.trailingAnchor.constraint(equalTo: clip.trailingAnchor).isActive = true
        form.topAnchor.constraint(equalTo: clip.topAnchor).isActive = true

        let defaults = NSButton(title: "Restore Defaults", target: self,
                                action: #selector(restoreDefaults(_:)))
        let cancel = NSButton(title: "Cancel", target: self, action: #selector(cancel(_:)))
        cancel.keyEquivalent = "\u{1b}"
        applyButton.target = self
        applyButton.action = #selector(apply(_:))
        let ok = NSButton(title: "OK", target: self, action: #selector(ok(_:)))
        ok.keyEquivalent = "\r"
        let buttons = NSStackView(views: [defaults, NSView(), cancel, applyButton, ok])
        buttons.orientation = .horizontal
        buttons.edgeInsets = NSEdgeInsets(top: 10, left: 20, bottom: 14, right: 20)

        let content = NSView()
        for v in [sideScroll, formScroll, buttons] as [NSView] {
            v.translatesAutoresizingMaskIntoConstraints = false
            content.addSubview(v)
        }
        let divider = NSBox()
        divider.boxType = .separator
        divider.translatesAutoresizingMaskIntoConstraints = false
        content.addSubview(divider)
        NSLayoutConstraint.activate([
            sideScroll.topAnchor.constraint(equalTo: content.topAnchor),
            sideScroll.leadingAnchor.constraint(equalTo: content.leadingAnchor),
            sideScroll.widthAnchor.constraint(equalToConstant: 180),
            sideScroll.bottomAnchor.constraint(equalTo: divider.topAnchor),
            formScroll.topAnchor.constraint(equalTo: content.topAnchor),
            formScroll.leadingAnchor.constraint(equalTo: sideScroll.trailingAnchor),
            formScroll.trailingAnchor.constraint(equalTo: content.trailingAnchor),
            formScroll.bottomAnchor.constraint(equalTo: divider.topAnchor),
            divider.leadingAnchor.constraint(equalTo: content.leadingAnchor),
            divider.trailingAnchor.constraint(equalTo: content.trailingAnchor),
            divider.bottomAnchor.constraint(equalTo: buttons.topAnchor),
            buttons.leadingAnchor.constraint(equalTo: content.leadingAnchor),
            buttons.trailingAnchor.constraint(equalTo: content.trailingAnchor),
            buttons.bottomAnchor.constraint(equalTo: content.bottomAnchor),
        ])
        window.contentView = content
    }

    // MARK: Sidebar

    func numberOfRows(in tableView: NSTableView) -> Int { Int(host.OptionsPageCount(kind)) }

    func tableView(_ tableView: NSTableView, viewFor tableColumn: NSTableColumn?,
                   row: Int) -> NSView? {
        let label = NSTextField(labelWithString: String(host.OptionsPageTitle(kind, Int32(row))))
        label.lineBreakMode = .byTruncatingTail
        let cell = NSTableCellView()
        cell.addSubview(label)
        cell.textField = label
        label.translatesAutoresizingMaskIntoConstraints = false
        NSLayoutConstraint.activate([
            label.leadingAnchor.constraint(equalTo: cell.leadingAnchor, constant: 4),
            label.trailingAnchor.constraint(equalTo: cell.trailingAnchor, constant: -4),
            label.centerYAnchor.constraint(equalTo: cell.centerYAnchor),
        ])
        return cell
    }

    func tableViewSelectionDidChange(_ notification: Notification) {
        let row = sidebar.selectedRow
        guard row >= 0, Int32(row) != page else { return }
        window?.makeFirstResponder(nil)  // commits a text field being edited
        page = Int32(row)
        showPage()
    }

    // MARK: The generated page

    /// Rebuilds the form for `page`: one grid of label and control rows, with
    /// a heading row spanning both columns where a section starts, so the
    /// columns line up across sections.
    private func showPage() {
        form.arrangedSubviews.forEach { $0.removeFromSuperview() }
        controls.removeAll()
        fieldIndex.removeAll()
        if host.OptionsPageCount(kind) == 0 {
            form.addArrangedSubview(NSTextField(labelWithString: "Nothing here has options yet."))
            updateApply()
            return
        }
        let grid = NSGridView(numberOfColumns: 2, rows: 0)
        grid.rowSpacing = 8
        grid.columnSpacing = 10
        grid.column(at: 0).xPlacement = .trailing
        form.addArrangedSubview(grid)
        var section: String?
        for i in 0..<host.OptionsFieldCount(kind, page) {
            let f = host.OptionsFieldAt(kind, page, i)
            let title = String(f.section)
            if title != section {
                section = title
                if !title.isEmpty {
                    let heading = NSTextField(labelWithString: title)
                    heading.font = .boldSystemFont(ofSize: NSFont.systemFontSize)
                    let row = grid.addRow(with: [heading, NSGridCell.emptyContentView])
                    row.mergeCells(in: NSRange(location: 0, length: 2))
                    heading.alignment = .left
                    row.cell(at: 0).xPlacement = .leading
                    if grid.numberOfRows > 1 { row.topPadding = 10 }
                }
            }
            let key = String(f.key)
            let control = makeControl(f, index: i)
            control.toolTip = f.help.empty() ? nil : String(f.help)
            controls[key] = control
            fieldIndex[key] = i
            let label = f.type == fv.desk.kFieldBool ? NSGridCell.emptyContentView
                : NSTextField(labelWithString: String(f.label) + ":")
            let row = grid.addRow(with: [label, control])
            // Colour wells and pop-ups have no text baseline to align to.
            row.rowAlignment = f.type == fv.desk.kFieldColor || f.type == fv.desk.kFieldChoice
                ? .none : .firstBaseline
            row.yPlacement = .center
        }
        updateApply()
    }

    /// One control for a field, its value set and its action wired.
    private func makeControl(_ f: fv.desk.HostOptionsField, index: Int32) -> NSView {
        let key = String(f.key)
        let id = NSUserInterfaceItemIdentifier(key)
        switch f.type {
        case fv.desk.kFieldBool:
            let b = NSButton(checkboxWithTitle: String(f.label), target: self,
                             action: #selector(fieldChanged(_:)))
            b.identifier = id
            fill(b, with: f)
            return b
        case fv.desk.kFieldColor:
            let well = NSColorWell(style: .default)
            well.identifier = id
            well.target = self
            well.action = #selector(fieldChanged(_:))
            fill(well, with: f)
            return well
        case fv.desk.kFieldChoice:
            let popup = NSPopUpButton(frame: .zero, pullsDown: false)
            for c in 0..<f.choice_count {
                popup.addItem(withTitle: String(host.OptionsChoiceLabel(kind, page, index, c)))
            }
            popup.identifier = id
            popup.target = self
            popup.action = #selector(fieldChanged(_:))
            fill(popup, with: f)
            return popup
        case fv.desk.kFieldPath:
            let text = textField(id: id, width: 260)
            fill(text, with: f)
            let choose = NSButton(title: "Choose\u{2026}", target: self,
                                  action: #selector(choosePath(_:)))
            choose.identifier = NSUserInterfaceItemIdentifier("choose:" + key)
            let row = NSStackView(views: [text, choose])
            row.orientation = .horizontal
            return row
        default:
            let numeric = f.type == fv.desk.kFieldInt || f.type == fv.desk.kFieldDouble
            let text = textField(id: id, width: numeric ? 90 : 260)
            if numeric {
                let fmt = NumberFormatter()
                fmt.numberStyle = .decimal
                fmt.usesGroupingSeparator = false
                fmt.allowsFloats = f.type == fv.desk.kFieldDouble
                fmt.maximumFractionDigits = f.type == fv.desk.kFieldDouble ? 6 : 0
                if f.min != f.max {
                    fmt.minimum = NSNumber(value: f.min)
                    fmt.maximum = NSNumber(value: f.max)
                }
                text.formatter = fmt
            }
            fill(text, with: f)
            guard f.type == fv.desk.kFieldInt, f.min != f.max else { return text }
            let stepper = NSStepper()
            stepper.minValue = f.min
            stepper.maxValue = f.max
            stepper.increment = 1
            stepper.valueWraps = false
            stepper.identifier = NSUserInterfaceItemIdentifier("step:" + key)
            stepper.target = self
            stepper.action = #selector(stepped(_:))
            stepper.doubleValue = Double(String(f.value)) ?? f.min
            let row = NSStackView(views: [text, stepper])
            row.orientation = .horizontal
            row.spacing = 4
            return row
        }
    }

    private func textField(id: NSUserInterfaceItemIdentifier, width: CGFloat) -> NSTextField {
        let t = NSTextField(string: "")
        t.identifier = id
        t.target = self
        t.action = #selector(fieldChanged(_:))
        // Commits on focus loss as well as Return.
        t.cell?.sendsActionOnEndEditing = true
        t.widthAnchor.constraint(equalToConstant: width).isActive = true
        return t
    }

    /// Shows the field's current value in `view`.
    private func fill(_ view: NSView, with f: fv.desk.HostOptionsField) {
        let value = String(f.value)
        switch view {
        case let b as NSButton where f.type == fv.desk.kFieldBool:
            b.state = value == "true" ? .on : .off
        case let w as NSColorWell:
            w.color = Self.color(value)
        case let p as NSPopUpButton:
            p.selectItem(at: Int(value) ?? 0)
        case let t as NSTextField:
            t.stringValue = value
        case let row as NSStackView:
            for v in row.arrangedSubviews {
                if let t = v as? NSTextField { t.stringValue = value }
                if let s = v as? NSStepper { s.doubleValue = Double(value) ?? s.minValue }
            }
        default:
            break
        }
    }

    // MARK: Actions

    @objc private func fieldChanged(_ sender: NSView) {
        guard let key = sender.identifier?.rawValue else { return }
        let value: String
        switch sender {
        case let b as NSButton: value = b.state == .on ? "true" : "false"
        case let w as NSColorWell:
            guard let text = Self.text(w.color) else {
                NSSound.beep()
                if let i = fieldIndex[key] { fill(w, with: host.OptionsFieldAt(kind, page, i)) }
                return
            }
            value = text
        case let p as NSPopUpButton: value = String(p.indexOfSelectedItem)
        case let t as NSTextField: value = Self.plain(t)
        default: return
        }
        set(key, value)
    }

    @objc private func stepped(_ sender: NSStepper) {
        guard let id = sender.identifier?.rawValue, id.hasPrefix("step:") else { return }
        set(String(id.dropFirst(5)), String(Int(sender.doubleValue)))
    }

    @objc private func choosePath(_ sender: NSButton) {
        guard let id = sender.identifier?.rawValue, id.hasPrefix("choose:"),
              let index = fieldIndex[String(id.dropFirst(7))], let window else { return }
        let f = host.OptionsFieldAt(kind, page, index)
        let panel = NSOpenPanel()
        panel.canChooseDirectories = f.directory
        panel.canChooseFiles = !f.directory
        panel.allowsMultipleSelection = false
        let current = String(f.value)
        if !current.isEmpty {
            panel.directoryURL = URL(fileURLWithPath: current).deletingLastPathComponent()
        }
        let key = String(f.key)
        panel.beginSheetModal(for: window) { [weak self] response in
            guard response == .OK, let url = panel.url else { return }
            MainActor.assumeIsolated { self?.set(key, url.path) }
        }
    }

    /// Offers a value to the model, then shows what it kept.
    private func set(_ key: String, _ value: String) {
        let error = String(host.SetOptionValue(kind, page, std.string(key), std.string(value)))
        if !error.isEmpty { NSSound.beep() }
        if let i = fieldIndex[key], let view = controls[key] {
            fill(view, with: host.OptionsFieldAt(kind, page, i))
        }
        updateApply()
    }

    private func updateApply() { applyButton.isEnabled = host.OptionsDirty(kind) }

    @objc private func restoreDefaults(_ sender: Any?) {
        let error = String(host.ResetOptionsPage(kind, page))
        if !error.isEmpty { NSSound.beep() }
        showPage()
    }

    /// Applies the changes; false (with an alert) when the core refused.
    @discardableResult
    private func applyChanges() -> Bool {
        window?.makeFirstResponder(nil)
        let error = String(host.ApplyOptions(kind))
        updateApply()
        guard error.isEmpty else {
            let alert = NSAlert()
            alert.alertStyle = .warning
            alert.messageText = "The options could not be saved"
            alert.informativeText = error
            if let window { alert.beginSheetModal(for: window) }
            return false
        }
        return true
    }

    @objc private func apply(_ sender: Any?) { applyChanges() }

    @objc private func ok(_ sender: Any?) {
        if applyChanges() { close() }
    }

    @objc private func cancel(_ sender: Any?) { close() }

    /// Closing by any route discards what was not applied.
    func windowWillClose(_ notification: Notification) {
        host.RevertOptions(kind)
        host.CloseOptions(kind)
        onClose?()
    }

    // MARK: Values

    /// The text of a field, without a number formatter's grouping.
    private static func plain(_ t: NSTextField) -> String {
        if t.formatter != nil, let n = t.objectValue as? NSNumber { return n.stringValue }
        return t.stringValue
    }

    /// "#RRGGBBAA" in sRGB; nil for a colour with no RGB form (a pattern).
    static func text(_ color: NSColor) -> String? {
        guard let c = color.usingColorSpace(.sRGB) else { return nil }
        let parts = [c.redComponent, c.greenComponent, c.blueComponent, c.alphaComponent]
        return "#" + parts.map { String(format: "%02X", Int(($0 * 255).rounded())) }.joined()
    }

    static func color(_ text: String) -> NSColor {
        guard text.hasPrefix("#"), text.count == 9, let v = UInt32(text.dropFirst(), radix: 16)
        else { return .black }
        func c(_ shift: UInt32) -> CGFloat { CGFloat((v >> shift) & 0xFF) / 255 }
        return NSColor(srgbRed: c(24), green: c(16), blue: c(8), alpha: c(0))
    }
}

/// Keeps a form pinned to the top of its scroll view.
private final class FlippedClipView: NSClipView {
    override var isFlipped: Bool { true }
}
